name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: mymindstorm/setup-emsdk@v14
        with:
          version: 3.1.67
          actions-cache-folder: .emsdk
      - uses: actions/setup-node@v4
        with:
          node-version: 22.2.0
          cache: npm
          cache-dependency-path: |
            package-lock.json
            wasmoon/package-lock.json
      - name: Build wasmoon
        working-directory: ./wasmoon
        run: |
          npm ci
          npm run build:wasm:dev
          npm run build
      - run: npm ci
      - run: npm run build
